from enum import Enum


class Labels(str, Enum):
    boss_lv_text = 'boss_lv_text'
    box_char_1 = 'box_char_1'
    box_char_2 = 'box_char_2'
    box_char_3 = 'box_char_3'
    box_char_4 = 'box_char_4'
    box_skill = 'box_skill'
    box_ultimate = 'box_ultimate'
    char_1_text = 'char_1_text'
    char_2_text = 'char_2_text'
    char_3_text = 'char_3_text'
    char_4_text = 'char_4_text'
    dialog_click = 'dialog_click'
    dialog_history = 'dialog_history'
    fish_bait = 'fish_bait'
    fish_start = 'fish_start'
    health_bar_slash = 'health_bar_slash'
    interactable = 'interactable'
    message = 'message'
    message_dialog = 'message_dialog'
    mini_map_arrow = 'mini_map_arrow'
    skip_dialog = 'skip_dialog'
    skip_quest_confirm = 'skip_quest_confirm'
